### ISSUE TITLE
Wrong path chrome.lnk in Chrome.ahk_v1.2(Release)

### ISSUE THREAD

**Issue by mschadev** [G33kDude/Chrome.ahk#13] opened 2019-12-31 04:57 UTC
###  script.ahk line 77

Wrong path
``HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Pahs\chrome.exe``

correct path
``HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe``

**Comment by G33kDude** [comment] 2020-05-28 15:54
Duplicate of #1

**Closed as completed by G33kDude** 2020-05-28 15:54 UTC

**Comment by Nirvanatin** [comment] 2022-05-14 10:01
There have been tons of wasted hours as a result of this typo.
